/*
 * constants.h
 *
 * Created: 24.05.2018 19:24:50
 *  Author: chrak_2
 */


#ifndef MYCONSTANTS_H_
#define MYCONSTANTS_H_


#include "RomId/RomId.h"
using namespace OneWire;

#define LED_ROT_ON		PORTA_OUTCLR = PIN2_bm
#define LED_ROT_OFF		PORTA_OUTSET = PIN2_bm
#define LED_ROT_TOGGLE	PORTA_OUTTGL = PIN2_bm
#define LED_GRUEN_ON		PORTA_OUTCLR = PIN3_bm
#define LED_GRUEN_OFF		PORTA_OUTSET = PIN3_bm
#define LED_GRUEN_TOGGLE	PORTA_OUTTGL = PIN3_bm

#define BROADCAST "BR"

typedef struct SensInfos SENSINFOS;

#define SENSOR_READY 0

enum{NOTHING_CLIMA_TODO=SENSOR_READY,
	START_TCONVERSION,WAIT_TCONVERSION,READ_TCONVERSION,
	START_HCONVERSION,WAIT_HCONVERSION,READ_HCONVERSION,
CALC_CONVERSION1,CALC_CONVERSION2,CALC_CONVERSION3};

enum{NOTHING_LAST_TODO=SENSOR_READY,WAIT_LAST,READY_LAST};

enum{KLIMASENSOR=0,LASTSENSOR};

#define REPORT_BETWEEN_SENSORS 20
#define REPORT_BETWEEN_BLOCKS  3000
#define WAIT_AFTER_LAST_SENSOR  300

enum{TEMPREPORT=0,HUMIREPORT,ABSHUMIREPORT,DEWPOINTREPORT,L1SWELLREPORT,L2SWELLREPORT,L1HYSTREPORT,L2HYSTREPORT,LASTREPORT};

#define NUMBER_OF_TEMPSENSORS 2
#define NUMBER_OF_SENSORS_NAME_LENGTH 12
#define NUMBER_STORED_SENSORS NUMBER_OF_TEMPSENSORS

struct SensInfos
{
	RomId romID;
	uint8_t number;
	uint16_t temperature_bits;
    uint8_t historyMax;
	char name[NUMBER_OF_SENSORS_NAME_LENGTH];
	double caliCoefficients[4];
};

typedef struct SensInfos SENSINFOS;

#endif /* MYCONSTANTS_H_ */
