/*
 * constants.h
 *
 * Created: 24.05.2018 19:24:50
 *  Author: chrak_2
 */


#ifndef MYCONSTANTS_H_
#define MYCONSTANTS_H_


#include "RomId/RomId.h"
using namespace OneWire;

#define LED_ROT_ON		PORTA_OUTCLR = PIN2_bm
#define LED_ROT_OFF		PORTA_OUTSET = PIN2_bm
#define LED_ROT_TOGGLE	PORTA_OUTTGL = PIN2_bm
#define LED_GRUEN_ON		PORTA_OUTCLR = PIN3_bm
#define LED_GRUEN_OFF		PORTA_OUTSET = PIN3_bm
#define LED_GRUEN_TOGGLE	PORTA_OUTTGL = PIN3_bm

#define LED_RGB_BLUE  0b10000000
#define LED_RGB_GREEN 0b01000000
#define LED_RGB_RED   0b00100000
#define POWER_3       0b00000100
#define POWER_2       0b00000010
#define POWER_1       0b00000001

#define BROADCAST "BR"

typedef struct SensInfos SENSINFOS;

#define SENSOR_READY 0

enum{NOTHING_CLIMA_TODO=SENSOR_READY,WAKEUP,WAIT_WAKEUP,
	START_CONVERSION,WAIT_CONVERSION,READ_CONVERSION,WAIT_READ,
	CALC_CONVERSION0,CALC_CONVERSION1,CALC_CONVERSION2};

enum{NOTHING_LAST_TODO=SENSOR_READY,WAIT_LAST,READY_LAST};

enum{KLIMASENSOR=0,LASTSENSOR};

enum{FAN_STATUS_OFF,FAN_STATUS_1,FAN_STATUS_2,FAN_STATUS_AUTO,FAN_STATUS_UNVALID = 255};

#define REPORT_BETWEEN_SENSORS 50
#define REPORT_BETWEEN_BLOCKS  3000
#define WAIT_AFTER_LAST_SENSOR  300

enum{TEMPREPORT=0,HUMIREPORT,ABSHUMIREPORT,DEWPOINTREPORT,L1SWELLREPORT,L2SWELLREPORT,L1HYSTREPORT,L2HYSTREPORT,FANACTUALSTATUSREPORT,FANSETSTATUSREPORT,LASTREPORT};

#define NUMBER_OF_TEMPSENSORS 2
#define NUMBER_OF_SENSORS_NAME_LENGTH 12
#define NUMBER_STORED_SENSORS NUMBER_OF_TEMPSENSORS

struct SensInfos
{
	RomId romID;
	uint8_t number;
	uint16_t temperature_bits;
    uint8_t historyMax;
	char name[NUMBER_OF_SENSORS_NAME_LENGTH];
	double caliCoefficients[4];
};

typedef struct SensInfos SENSINFOS;

#endif /* MYCONSTANTS_H_ */
